version: '1.0'

services:
  postgres:
    container_name: postgres
    image: postgres:15
    hostname: postgres
    ports:
      - 5431:5431
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
