version: '1.0'

services:
  postgres:
    container_name: postgres
    image: postgres:15
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    container_name: server-dev
    image: server-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - postgres

volumes:
  postgres-data:
