version: "1.0"

services:
  redis:
    container_name: redis
    image: redis:7-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  server:
    container_name: server-dev
    image: server-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/server/src
    ports:
      - 4000:4000
    depends_on:
      - redis
